Repository ferredoxin/QNotified, pull requests merged in 2021-04, with the labels that each got.

#798 Add HideTab
  app/src/main/java/ltd/nextalone/util/ViewUtils.kt
  app/src/main/java/me/ketal/hook/HideTab.kt
  app/src/main/java/nil/nadph/qnotified/activity/BetaTestFuncActivity.java
Labels: Feature

#801 Fix CheatHook if open cmshow
  app/src/main/java/cc/ioctl/hook/CheatHook.java
Labels: Bug

#807 Update UI framework in qn_kernel
  app/src/main/java/me/kyuubiran/hook/AutoMosaicName.kt
  app/src/main/java/me/kyuubiran/hook/ShowSelfMsgByLeft.kt
  app/src/main/java/me/singleneuron/hook/ChangeDrawerWidth.kt
  app/src/main/java/me/singleneuron/hook/decorator/RegexAntiMeg.kt
  app/src/main/java/me/singleneuron/qn_kernel/base/CommonDelayAbleHookBridge.kt
  app/src/main/java/me/singleneuron/qn_kernel/decorator/BaseDecorator.kt
  app/src/main/java/me/singleneuron/qn_kernel/tlb/UiTable.kt
  app/src/main/java/me/singleneuron/qn_kernel/ui/NewSettingsActivity.kt
  app/src/main/java/me/singleneuron/qn_kernel/ui/SettingsFragment.kt
  app/src/main/java/me/singleneuron/qn_kernel/ui/base/Preference.kt
  app/src/main/java/me/singleneuron/qn_kernel/ui/base/UiDSLHelper.kt
  app/src/main/java/me/singleneuron/qn_kernel/ui/base/UiFactory.kt
  app/src/main/java/me/singleneuron/qn_kernel/ui/base/UiInterface.kt
  app/src/main/java/me/singleneuron/util/UiHelper.kt
Labels: Kernel, UI

#822 Update Version Code
  .github/workflows/ci.yml
  app/build.gradle
Labels: Document

#823 Improve UI framework in qn_kernel
  app/build.gradle
  app/src/main/java/me/singleneuron/hook/ChangeDrawerWidth.kt
  app/src/main/java/me/singleneuron/hook/decorator/RegexAntiMeg.kt
  app/src/main/java/me/singleneuron/qn_kernel/base/CommonDelayAbleHookBridge.kt
  app/src/main/java/me/singleneuron/qn_kernel/decorator/BaseDecorator.kt
  app/src/main/java/me/singleneuron/qn_kernel/decorator/BaseItemBuilderFactoryHookDecorator.kt
  app/src/main/java/me/singleneuron/qn_kernel/decorator/BaseStartActivityHookDecorator.kt
  app/src/main/java/me/singleneuron/qn_kernel/ui/NewSettingsActivity.kt
  app/src/main/java/me/singleneuron/qn_kernel/ui/SettingsFragment.kt
  app/src/main/java/me/singleneuron/qn_kernel/ui/base/Preference.kt
  app/src/main/java/me/singleneuron/qn_kernel/ui/base/UiDSLHelper.kt
  app/src/main/java/me/singleneuron/qn_kernel/ui/base/UiFactory.kt
  app/src/main/java/nil/nadph/qnotified/ui/ViewBuilder.java
Labels: Kernel, UI

#824 Mark ExfriendManager as Deprecated
  app/src/main/java/nil/nadph/qnotified/ExfriendManager.java
Labels: Document

#837 lint README.md and add release channels
  README.md
Labels: Document

#841 Update README.md
  README.md
Labels: Document, Skip CI
