Repository ferredoxin/QNotified, pull requests merged in 2021-02, with the labels that each got.

#530 Unify the code style into Google Style
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
Labels: doc

#527 Refactor Utils.java
  app/src/main/java/me/ketal/hook/LeftSwipeReplyHook.java
  app/src/main/java/me/ketal/hook/MultiActionHook.java
  app/src/main/java/me/ketal/hook/SortAtPanel.java
  app/src/main/java/nil/nadph/qnotified/InjectDelayableHooks.java
  app/src/main/java/nil/nadph/qnotified/MainHook.java
  app/src/main/java/nil/nadph/qnotified/activity/SettingsActivity.java
  app/src/main/java/nil/nadph/qnotified/hook/BlockFluxThief.java
  app/src/main/java/nil/nadph/qnotified/hook/FlashPicHook.java
  app/src/main/java/nil/nadph/qnotified/hook/InputButtonHook.java
  app/src/main/java/nil/nadph/qnotified/hook/InspectMessage.java
  app/src/main/java/nil/nadph/qnotified/hook/MultiForwardAvatarHook.java
  app/src/main/java/nil/nadph/qnotified/hook/SettingEntryHook.java
  app/src/main/java/nil/nadph/qnotified/util/ReflexUtil.java
  app/src/main/java/nil/nadph/qnotified/util/Utils.java
Labels: feature

#531 [skip ci] update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: document

#538 Update Android NDK
  app/build.gradle
Labels: C, bug

#537 Update SimplifyChatLongItem
  app/src/main/java/me/nextalone/hook/SimplifyChatLongItem.kt
  app/src/main/java/nil/nadph/qnotified/activity/SettingsActivity.java
  app/src/main/java/nil/nadph/qnotified/hook/AbsDelayableHook.java
Labels: bug, feature

#542 Fix active statue error for unknown reason
  app/src/main/java/me/singleneuron/util/HookStatue.kt
  app/src/main/java/nil/nadph/qnotified/startup/HookEntry.java
  app/src/main/java/nil/nadph/qnotified/util/Utils.java
Labels: bug

#543 Change HookStatue's copyleft
  app/src/main/java/me/singleneuron/util/HookStatue.kt
Labels: document

#550 Add IDEA automatically add code headers
  .idea/copyright/license.xml
  .idea/copyright/profiles_settings.xml
  CONTRIBUTING.md
Labels: Document, N

#549 Add Auto close issue that don't follow issue template
  .github/workflows/auto_close_issues.yml
Labels: Document, N

#548 Add Auto close issue that don't follow issue template
  .github/workflows/auto_close_issues.yml
Labels: Document, N

#556 Add three ChineseNewYear icons
  app/ChineseNewYearIcons/icon_QNotified_GoogleStyle_春节欠1.0版_512x512.png
  app/ChineseNewYearIcons/icon_QNotified_GoogleStyle_春节欠展望未来_512x512.png
  app/ChineseNewYearIcons/icon_QNotified_GoogleStyle_春节欠新版UI_512x512.png
  app/build.gradle
Labels: Document

#555 Add copyright information for eula
  app/src/main/assets/eula.txt
  app/src/main/java/nil/nadph/qnotified/activity/EulaActivity.java
Labels: Document

#553 Update SimplifyChatLongItem
  app/src/main/java/me/ketal/hook/SendFavoriteHook.kt
  app/src/main/java/me/nextalone/hook/SimplifyChatLongItem.kt
  app/src/main/java/nil/nadph/qnotified/activity/SettingsActivity.java
Labels: Bug, N

#557 Add markdown version of eula
  app/src/main/assets/eula.md
Labels: Document

#561 Change the label of the Issue template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature-request.md
Labels: Bug, Document

#570 Fixed SimplifyChatLongItem
  app/src/main/java/me/nextalone/hook/SimplifyChatLongItem.kt
Labels: Bug

#571 Add SimplifyQQSettings
  app/src/main/java/me/nextalone/hook/SimplifyQQSettings.kt
  app/src/main/java/me/nextalone/util/Utils.kt
  app/src/main/java/nil/nadph/qnotified/activity/SettingsActivity.java
  app/src/main/java/nil/nadph/qnotified/hook/AbsDelayableHook.java
  app/src/main/res/xml/pref_sidebar.xml
Labels: Feature

#573 Add SimplifyPlusPanel
  app/src/main/java/me/nextalone/hook/SimplifyPlusPanel.kt
  app/src/main/java/nil/nadph/qnotified/activity/SettingsActivity.java
  app/src/main/java/nil/nadph/qnotified/hook/AbsDelayableHook.java
Labels: Feature

#566 Add validator to button in SettingsActivity
  app/src/main/java/cc/ioctl/hook/FavMoreEmo.java
  app/src/main/java/nil/nadph/qnotified/activity/SettingsActivity.java
  app/src/main/java/nil/nadph/qnotified/ui/ViewBuilder.java
Labels: Feature

#577 修复TIM中模块设置界面黑屏
  app/src/main/java/nil/nadph/qnotified/ui/ViewBuilder.java
Labels: Bug, C, UI

#575 Add more lost items in SimplifyPlusPanel
  app/src/main/java/me/nextalone/hook/SimplifyPlusPanel.kt
Labels: Bug, Feature

#576 Add Tips on Play Version QQ
  app/src/main/java/me/kyuubiran/hook/RemovePlayTogether.java
  app/src/main/java/me/singleneuron/qn_kernel/data/HostInformationProvider.kt
  app/src/main/java/nil/nadph/qnotified/activity/SettingsActivity.java
Labels: Kernel, UI

#579 Add mute message
  app/src/main/java/cn/lliiooll/hook/AntiMessage.kt
  app/src/main/java/cn/lliiooll/hook/MessageInterception.kt
  app/src/main/java/cn/lliiooll/msg/MessageManager.java
  app/src/main/java/cn/lliiooll/msg/MessageReceiver.java
  app/src/main/java/cn/lliiooll/util/BiMap.java
  app/src/main/java/cn/lliiooll/util/HashBiMap.java
  app/src/main/java/cn/lliiooll/util/MsgRecordUtil.java
  app/src/main/java/nil/nadph/qnotified/activity/SettingsActivity.java
  app/src/main/java/nil/nadph/qnotified/hook/AbsDelayableHook.java
Labels: Feature

#583 Show and sort description to AntiMessage
  app/src/main/java/cn/lliiooll/hook/AntiMessage.kt
  app/src/main/java/cn/lliiooll/util/MsgRecordUtil.java
  app/src/main/java/ltd/nextalone/base/MultiItemDelayableHook.kt
Labels: Feature

#585 Add mute troop at all msg in AntiMessage and remove sth in SettingsActivity
  app/src/main/java/cn/lliiooll/hook/AntiMessage.kt
  app/src/main/java/cn/lliiooll/util/MsgRecordUtil.java
  app/src/main/java/nil/nadph/qnotified/activity/SettingsActivity.java
Labels: Bug, Feature

#586 Fix NPE in Settings Activity caused by OnResume
  app/src/main/java/nil/nadph/qnotified/activity/SettingsActivity.java
Labels: Bug, C

#592 Add new hook api demo
  app/src/main/java/me/singleneuron/qn_kernel/annotation/HookLoadable.kt
  app/src/main/java/me/singleneuron/qn_kernel/annotation/ModuleInfo.java
  app/src/main/java/me/singleneuron/qn_kernel/data/ModuleInfo.kt
  app/src/main/java/me/singleneuron/qn_kernel/demo/AnotherJavaHook.java
  app/src/main/java/me/singleneuron/qn_kernel/demo/JavaHook.java
  app/src/main/java/me/singleneuron/qn_kernel/demo/KotlinHook.kt
Labels: Document, Kernel

#601 modify author name
  app/src/main/res/values/strings.xml
Labels: Document

#615 Update and rename LICENSE to LICENSE.md
  LICENSE
  LICENSE.md
  eula.md
Labels: Document

#617 Add ChatItemShowQQUin
  app/src/main/java/me/ketal/hook/ChatItemShowQQUin.kt
  app/src/main/java/nil/nadph/qnotified/activity/SettingsActivity.java
  app/src/main/java/nil/nadph/qnotified/hook/AbsDelayableHook.java
Labels: Feature

#618 Add Simplify Contact Tabs for QQ 8.5.5
  app/src/main/java/ltd/nextalone/hook/ChatWordsCount.kt
  app/src/main/java/ltd/nextalone/hook/SimplifyContactTabs.kt
  app/src/main/java/ltd/nextalone/util/Utils.kt
  app/src/main/java/nil/nadph/qnotified/activity/SettingsActivity.java
  app/src/main/java/nil/nadph/qnotified/hook/AbsDelayableHook.java
Labels: Feature

#642 Make time changeable to AutoRenewFire
  app/src/main/java/me/kyuubiran/dialog/AutoRenewFireDialog.kt
  app/src/main/java/me/kyuubiran/util/AutoRenewFireMgr.kt
Labels: Feature

#643 Update EnableQLog
  app/src/main/java/ltd/nextalone/hook/EnableQLog.kt
  app/src/main/java/ltd/nextalone/util/LogUtils.kt
  app/src/main/java/ltd/nextalone/util/Utils.kt
Labels: Feature

#644 [skip ci] Add More Feature to Readme.md
  README.md
Labels: Document

#645 Add Simplify Emo Panel for QQ 8.5.5
  app/src/main/java/ltd/nextalone/hook/SimplifyEmoPanel.kt
  app/src/main/java/nil/nadph/qnotified/activity/SettingsActivity.java
Labels: Feature

#646 Set simplify mode to remove, refactor MultiItemDelayableHook, and Add SimplifyRecentDialog for QQ 8.5.5
  app/src/main/java/cn/lliiooll/hook/AntiMessage.kt
  app/src/main/java/ltd/nextalone/base/MultiItemDelayableHook.kt
  app/src/main/java/ltd/nextalone/hook/SimplifyChatLongItem.kt
  app/src/main/java/ltd/nextalone/hook/SimplifyContactTabs.kt
  app/src/main/java/ltd/nextalone/hook/SimplifyPlusPanel.kt
  app/src/main/java/ltd/nextalone/hook/SimplifyQQSettings.kt
  app/src/main/java/ltd/nextalone/hook/SimplifyRecentDialog.kt
  app/src/main/java/ltd/nextalone/util/LogUtils.kt
  app/src/main/java/ltd/nextalone/util/Utils.kt
  app/src/main/java/nil/nadph/qnotified/activity/SettingsActivity.java
Labels: Feature

#657 添加卡片消息文本化
  app/src/main/java/me/singleneuron/hook/decorator/CardMsgToText.kt
  app/src/main/java/me/singleneuron/qn_kernel/dispacher/ItemBuilderFactoryHook.kt
  app/src/main/java/nil/nadph/qnotified/activity/SettingsActivity.java
Labels: Feature

#655 添加 特别关心消息单独分组
  app/src/main/java/me/singleneuron/hook/SpecialCareNewChannel.kt
  app/src/main/java/me/singleneuron/util/KotlinUtils.kt
  app/src/main/java/nil/nadph/qnotified/activity/LicenseActivity.java
  app/src/main/java/nil/nadph/qnotified/activity/SettingsActivity.java
Labels: Feature

#656 增加万象屏蔽卡片消息
  app/src/main/java/cn/lliiooll/hook/AntiMessage.kt
  app/src/main/java/cn/lliiooll/hook/MessageInterception.kt
  app/src/main/java/cn/lliiooll/msg/MessageManager.java
  app/src/main/java/cn/lliiooll/msg/MessageReceiver.java
  app/src/main/java/me/kyuubiran/hook/testhook/CutMessage.kt
  app/src/main/java/me/singleneuron/hook/decorator/RegexAntiMeg.kt
  app/src/main/java/me/singleneuron/qn_kernel/data/MsgRecordData.kt
  app/src/main/java/nil/nadph/qnotified/activity/SettingsActivity.java
Labels: Feature

#660 添加 小程序转链接
  app/src/main/java/me/singleneuron/data/MiniAppArkData.kt
  app/src/main/java/me/singleneuron/data/StructMsgData.kt
  app/src/main/java/me/singleneuron/hook/decorator/CardMsgToText.kt
  app/src/main/java/me/singleneuron/hook/decorator/MiniAppToStruckMsg.kt
  app/src/main/java/me/singleneuron/qn_kernel/dispacher/ItemBuilderFactoryHook.kt
  app/src/main/java/nil/nadph/qnotified/activity/SettingsActivity.java
  app/src/main/java/nil/nadph/qnotified/util/Utils.java
Labels: Feature

#680 [skip ci]Delete Unused Files
  .travis.yml
Labels: Document

#688 Update MainActivity
  app/src/main/java/nil/nadph/qnotified/activity/MainActivity.kt
Labels: UI
