Repository ferredoxin/QNotified, pull requests merged in 2021-08, with the labels that each got.

#1009 fix: sendCardMsg's switch invalidation
  app/src/main/java/cc/ioctl/hook/InputButtonHook.java
Labels: H

#1011 fix: ConfigV2Activity crash
  app/src/main/res/layout/main_v2.xml
Labels: UI

#1045 Fix RemoveGroupApp for QQ 8.8.20 and earlier versions
  app/src/main/java/ltd/nextalone/hook/CleanRecentChat.kt
  app/src/main/java/me/kyuubiran/hook/RemoveGroupApp.kt
Labels: Fix

#1044 Block "qq.com" in FxxkQQBrowser
  app/src/main/java/me/singleneuron/hook/decorator/FxxkQQBrowser.kt
Labels: H, Fix
