Repository ferredoxin/QNotified, pull requests merged in 2021-03, with the labels that each got.

#691 Add new photo preview support for AutoSendOriginalPhoto
  app/src/main/java/ltd/nextalone/hook/AutoSendOriginalPhoto.kt
  app/src/main/java/ltd/nextalone/util/Utils.kt
Labels: Feature

#726 Change to use origin icons
  app/build.gradle
Labels: UI

#767 [skip ci]Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: Document

#760 Support QQ 8.6.0
  app/src/main/java/cc/ioctl/hook/CheatHook.java
  app/src/main/java/cc/ioctl/hook/MutePokePacket.java
  app/src/main/java/cc/ioctl/hook/ReplyNoAtHook.java
  app/src/main/java/ltd/nextalone/hook/ChatWordsCount.kt
  app/src/main/java/ltd/nextalone/hook/CollapseTroopMessage.kt
  app/src/main/java/ltd/nextalone/hook/DisabledRedNick.kt
  app/src/main/java/ltd/nextalone/hook/HideChatVipImage.kt
  app/src/main/java/ltd/nextalone/hook/HideOnlineNumber.kt
  app/src/main/java/ltd/nextalone/hook/HideOnlineStatus.kt
  app/src/main/java/ltd/nextalone/hook/HideProfileBubble.kt
  app/src/main/java/ltd/nextalone/hook/HideTotalNumber.kt
  app/src/main/java/ltd/nextalone/hook/HideTroopLevel.kt
  app/src/main/java/ltd/nextalone/hook/RemoveBottomRedDots.kt
  app/src/main/java/ltd/nextalone/hook/RemoveShortCutBar.kt
  app/src/main/java/ltd/nextalone/hook/SimplifyBottomQzone.kt
  app/src/main/java/ltd/nextalone/hook/SimplifyChatLongItem.kt
  app/src/main/java/ltd/nextalone/hook/SimplifyEmoPanel.kt
  app/src/main/java/ltd/nextalone/hook/SimplifyRecentDialog.kt
  app/src/main/java/ltd/nextalone/util/HookUtils.kt
  app/src/main/java/me/ketal/dispacher/BaseBubbleBuilderHook.kt
  app/src/main/java/me/ketal/hook/ChatItemShowQQUin.kt
  app/src/main/java/me/ketal/hook/FakeBalance.kt
  app/src/main/java/me/ketal/hook/HideFriendCardSendGift.kt
  app/src/main/java/me/ketal/util/TIMVersion.java
  app/src/main/java/me/kyuubiran/hook/RemoveDailySign.kt
  app/src/main/java/me/kyuubiran/hook/SimplifyQQSettingMe.kt
  app/src/main/java/me/singleneuron/qn_kernel/tlb/QQConfigTable.kt
  app/src/main/java/me/singleneuron/util/QQVersion.java
  app/src/main/java/nil/nadph/qnotified/MainHook.java
  app/src/main/java/nil/nadph/qnotified/activity/BetaTestFuncActivity.java
  app/src/main/java/nil/nadph/qnotified/bridge/ChatActivityFacade.java
  app/src/main/java/nil/nadph/qnotified/bridge/QQMessageFacade.java
  app/src/main/java/nil/nadph/qnotified/bridge/SessionInfoImpl.java
  app/src/main/java/nil/nadph/qnotified/ui/ResUtils.java
  app/src/main/java/nil/nadph/qnotified/util/DexKit.java
  app/src/main/java/nil/nadph/qnotified/util/Initiator.java
Labels: Bug
